"""A/B reversal VR Foraging curriculum — the simple sibling of ``curriculum.py``.

What this does
--------------
Same idea as ``curriculum.py``: ``build_trainer_state()`` **ignores any incoming
trainer_state** and builds a fresh one from the **graduated** stage of the real
``LearningSets`` curriculum (`aind_behavior_vr_foraging_curricula.learning_sets`). What
changes is the sequence:

* **Only two odors.** ``ODOR_A`` and ``ODOR_B`` (channels 0 and 1). The 7-odor pair
  generator (``get_odor_sequence``) is dropped entirely — there is nothing to sample.
* **Every block is a reversal.** Block 0 rewards A and not B; block 1 rewards B and not A;
  block 2 rewards A again, … Each block is ``REWARDED_PER_BLOCK`` rewarded sites +
  ``NON_REWARDED_PER_BLOCK`` non-rewarded sites, shuffled together.
* **Contrast flips with the reversal.** The visual contrast (the "context") alternates in
  lockstep with the block parity, so the context cue perfectly predicts which odor is
  rewarded: A-rewarded blocks render at ``CONTEXT_CONTRASTS[0]``, B-rewarded blocks at
  ``CONTEXT_CONTRASTS[1]``.

    block 0:  A+ B-   contrast CONTEXT_CONTRASTS[0]
    block 1:  B+ A-   contrast CONTEXT_CONTRASTS[1]
    block 2:  A+ B-   contrast CONTEXT_CONTRASTS[0]
    ...

As in ``curriculum.py``, a site's contrast lives in its patch definition and
``patch_indices`` only references patches by ``state_index``, so the patch list is
duplicated once per context: 4 patches (A/B × rewarded/non-rewarded) → 8. Context 1's
copies carry ``state_index += 14`` (the graduated stage's full patch count, so the original
``odor + 7 * is_rewarded`` convention is preserved inside each context) and a ``_ctx1``
label suffix. Everything stays a single schema-level ``Block``; "block" below means one
chunk of the sequence.

Where the base comes from
-------------------------
`graduated_task_logic()` returns the **real** graduated-stage task logic from
``aind_behavior_vr_foraging_curricula.learning_sets.stages.make_s_graduated`` — a
``SequenceEnvironment`` of single-reward-site patches (stop duration fixed at 3 s, velocity
at the floor, full geometry). Only the A/B patches of that list are kept; the other 5 odors'
patch definitions are dropped, so no other odor channel can ever be played.

⚠️ Worth reviewing
------------------
* The cross-session ``start_policies`` of the real graduated stage
  (``p_introduce_negative_sites``, ``p_water_cap``) are **dropped**: this is a one-shot
  manual injection of a static ``TrainerState``, not a run through the ``Trainer``, so no
  policies fire. Only the graduated stage's *task logic* (the environment) is reused.
* ``RenderSpecification.contrast`` is constrained to **[0, 1]** by the task schema, so the
  two contexts are mapped onto that range — tune ``CONTEXT_CONTRASTS`` to taste.
* Rewarded patches keep the graduated stage's reward probability (1.0) and non-rewarded
  patches keep theirs (0.0). Only *which odor* is which flips, not the probabilities.

Targets aind-behavior-vr-foraging >= 1.2 and aind-behavior-vr-foraging-curricula >= 1.2
(SequenceEnvironment / learning_sets API).
"""

from __future__ import annotations

import random

from aind_behavior_curriculum import Stage, TrainerState

import aind_behavior_vr_foraging.task_logic as vr
from aind_behavior_vr_foraging.task_logic import AindVrForagingTaskLogic
from aind_behavior_vr_foraging_curricula import __semver__ as _CURRICULA_VERSION
from aind_behavior_vr_foraging_curricula.learning_sets import helpers as ls
from aind_behavior_vr_foraging_curricula.learning_sets.curriculum import CURRICULUM_NAME as _BASE_CURRICULUM_NAME
from aind_behavior_vr_foraging_curricula.learning_sets.stages import make_s_graduated

# --------------------------------------------------------------------------------------
# Knobs to review
# --------------------------------------------------------------------------------------

#: The only two odors used, as olfactometer channel indices (0 <= index < ls.ODOR_COUNT).
ODOR_A: int = 0
ODOR_B: int = 1

#: The contrast "contexts", one per reversal phase, flipped in lockstep with the block
#: parity: index 0 = A-rewarded blocks, index 1 = B-rewarded blocks. Contrast is bounded
#: [0, 1] in the schema. Set both entries to the same value to disable the context cue.
CONTEXT_CONTRASTS: tuple[float, float] = (0.5, 1.0)

#: Sites per block. Y rewarded + Z non-rewarded, shuffled together. Fixed for every block.
REWARDED_PER_BLOCK: int = 5  # Y
NON_REWARDED_PER_BLOCK: int = 5  # Z

#: Number of blocks (reversals) to generate for the session.
N_BLOCKS: int = ls.N_PAIRS

#: Whether this suggestion should be flagged as generated by a curriculum. This is a manual,
#: off-curriculum injection, so False (the rig will still run `stage.task`, just logs a warning).
IS_ON_CURRICULUM: bool = False


# --------------------------------------------------------------------------------------
# Base: the real graduated stage of the LearningSets curriculum
# --------------------------------------------------------------------------------------

def _default_stage_name() -> str:
    """Descriptive default name, auto-filled from the knobs.

    Records the base curriculum this derives from (name + version), even though the injected
    ``TrainerState`` keeps ``curriculum=None`` / ``is_on_curriculum=False``.
    Example: ``manual_LearningSets_v1.2.0_ABReversal_odor0v1_5Rew_5NonRew``.
    """
    return (
        f"manual_{_BASE_CURRICULUM_NAME}_v{_CURRICULA_VERSION}_"
        f"ABReversal_odor{ODOR_A}v{ODOR_B}_"
        f"{REWARDED_PER_BLOCK}Rew_{NON_REWARDED_PER_BLOCK}NonRew"
    )


def graduated_task_logic() -> AindVrForagingTaskLogic:
    """Return the real graduated-stage task logic from the LearningSets curriculum.

    This is `aind_behavior_vr_foraging_curricula.learning_sets.stages.make_s_graduated`'s
    task: a `SequenceEnvironment` of 14 single-reward-site patches (7 odors × rewarded /
    non-rewarded) at the graduated settings (3 s stop, velocity floor, full geometry).
    """
    return make_s_graduated().task


# --------------------------------------------------------------------------------------
# Transforms: A/B-only patches per context + alternating reversal sequence
# --------------------------------------------------------------------------------------

def _is_ab_patch(patch: vr.Patch) -> bool:
    """True for the 4 graduated patches built on ``ODOR_A`` / ``ODOR_B``.

    The graduated ``state_index`` convention is ``odor_index + ODOR_COUNT * is_rewarded``,
    so the odor is recoverable as ``state_index % ODOR_COUNT``.
    """
    return patch.state_index % ls.ODOR_COUNT in (ODOR_A, ODOR_B)


def _context_patches(base_patches: list[vr.Patch], contrast: float, offset: int, ctx: int) -> list[vr.Patch]:
    """One context's copy of the A/B patches: deep-copied, ``state_index`` shifted by
    ``offset`` (so contexts don't collide), and every virtual-site generator set to ``contrast``."""
    out: list[vr.Patch] = []
    for p in base_patches:
        cp = p.model_copy(deep=True)
        cp.state_index = p.state_index + offset
        cp.label = f"{p.label}_ctx{ctx}"
        gens = cp.patch_virtual_sites_generator
        for gen in (gens.inter_site, gens.inter_patch, gens.reward_site, gens.post_patch):
            if gen is not None:
                gen.render_specification.contrast = contrast
        out.append(cp)
    return out


def _reversal_sequence(n_base: int) -> list[int]:
    """Build the ``patch_indices`` play order.

    Block ``i`` rewards A on even ``i`` and B on odd ``i``, with the non-rewarded odor being
    the other one; the context (and therefore the contrast) is the same parity, so the
    duplicated patch copy referenced is ``ctx = i % 2``. Each block emits
    ``NON_REWARDED_PER_BLOCK`` non-rewarded sites + ``REWARDED_PER_BLOCK`` rewarded sites,
    shuffled together.
    """
    sequence: list[int] = []
    for i in range(N_BLOCKS):
        pos, neg = (ODOR_A, ODOR_B) if i % 2 == 0 else (ODOR_B, ODOR_A)
        offset = (i % len(CONTEXT_CONTRASTS)) * n_base
        block_sites = (
            [neg + offset] * NON_REWARDED_PER_BLOCK
            + [pos + ls.ODOR_COUNT + offset] * REWARDED_PER_BLOCK
        )
        random.shuffle(block_sites)
        sequence.extend(block_sites)
    return sequence


# --------------------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------------------

def build_trainer_state(stage_name: str | None = None) -> TrainerState:
    """Build the TrainerState to inject. Ignores any existing/incoming trainer state.

    Args:
        stage_name: optional name for the emitted stage.

    Returns:
        A TrainerState whose task is the real graduated learning-set stage, restricted to
        odors A and B, with one patch copy per contrast context and a single-block sequence
        that reverses the rewarded odor (and the context) every block.
    """
    graduated = graduated_task_logic()
    base_env = graduated.task_parameters.environment.blocks[0].environment
    assert isinstance(base_env, vr.SequenceEnvironment), (
        f"Expected the graduated stage to use a SequenceEnvironment, got {type(base_env).__name__}"
    )
    # ``n_base`` is the *full* graduated patch count (14), not the filtered one: using it as
    # the per-context offset keeps each context's state_index on the original
    # ``odor + ODOR_COUNT * is_rewarded`` grid.
    n_base = len(base_env.patches)
    ab_patches = [p for p in base_env.patches if _is_ab_patch(p)]
    assert len(ab_patches) == 4, f"Expected 4 A/B patches in the graduated stage, got {len(ab_patches)}"

    patches: list[vr.Patch] = []
    for ctx, contrast in enumerate(CONTEXT_CONTRASTS):
        patches.extend(_context_patches(ab_patches, contrast, ctx * n_base, ctx))

    env = vr.SequenceEnvironment(
        patches=patches,
        sampling_mode=base_env.sampling_mode,
        patch_indices=_reversal_sequence(n_base),
    )

    task = graduated.model_copy(deep=True)
    task.task_parameters.environment = vr.BlockStructure(
        blocks=[vr.Block(environment=env)],
        sampling_mode="Sequential",
    )

    name = stage_name or _default_stage_name()
    task.stage_name = name
    stage = Stage(name=name, task=task)
    return TrainerState(
        stage=stage,
        curriculum=None,
        is_on_curriculum=IS_ON_CURRICULUM,
        active_policies=[],
    )


if __name__ == "__main__":
    # Quick self-check: build, round-trip, and verify the reversal rules hold.
    ts = build_trainer_state()
    env = ts.stage.task.task_parameters.environment.blocks[0].environment

    # state_index -> (odor, is_rewarded, contrast), read off each patch.
    info = {
        p.state_index: (
            p.state_index % ls.ODOR_COUNT,
            (p.state_index % (ls.ODOR_COUNT * 2)) >= ls.ODOR_COUNT,
            p.patch_virtual_sites_generator.reward_site.render_specification.contrast,
        )
        for p in env.patches
    }
    per_block = REWARDED_PER_BLOCK + NON_REWARDED_PER_BLOCK
    idx = env.patch_indices
    n_blocks = len(idx) // per_block

    assert {odor for odor, _, _ in info.values()} == {ODOR_A, ODOR_B}, "only A and B may exist"

    for block_i in range(min(n_blocks, 6)):  # spot-check the first few blocks
        chunk = idx[block_i * per_block : (block_i + 1) * per_block]
        rewarded = {info[s][0] for s in chunk if info[s][1]}
        non_rewarded = {info[s][0] for s in chunk if not info[s][1]}
        contrasts = {info[s][2] for s in chunk}
        expected_pos, expected_neg = (ODOR_A, ODOR_B) if block_i % 2 == 0 else (ODOR_B, ODOR_A)
        assert rewarded == {expected_pos}, (block_i, rewarded)
        assert non_rewarded == {expected_neg}, (block_i, non_rewarded)
        assert sum(1 for s in chunk if info[s][1]) == REWARDED_PER_BLOCK, block_i
        assert sum(1 for s in chunk if not info[s][1]) == NON_REWARDED_PER_BLOCK, block_i
        assert contrasts == {CONTEXT_CONTRASTS[block_i % 2]}, (block_i, contrasts)  # flips with reversal

    TrainerState.model_validate_json(ts.model_dump_json())  # raises if invalid
    print(
        f"OK: 1 block, {len(env.patches)} patches "
        f"({len(CONTEXT_CONTRASTS)} contexts × 4 A/B), {n_blocks} reversals, "
        f"{per_block}/block ({REWARDED_PER_BLOCK}+{NON_REWARDED_PER_BLOCK}), "
        f"odors {{{ODOR_A}, {ODOR_B}}} only, contrast flips with the reversal."
    )
