"""Custom VR Foraging curriculum — built on the real LearningSets graduated stage.

What this does
--------------
`build_trainer_state()` **ignores any incoming trainer_state** and builds a fresh one from
scratch that starts from the **graduated** stage of the real ``LearningSets`` curriculum
(`aind_behavior_vr_foraging_curricula.learning_sets`), keeps its odor-pair generation, and
adds two rules:

The odor-pair "blocks" are generated exactly as before — ``get_odor_sequence`` yields
``(negative, positive)`` odor-index pairs under the same rules (no odor reappears in the
previous pair). On top of that:

1. **Fixed sites per pair** — each pair contributes a fixed ``REWARDED_PER_PAIR`` rewarded
   (positive) sites and ``NON_REWARDED_PER_PAIR`` non-rewarded (negative) sites, shuffled
   together (both parameterized). This replaces the graduated stage's ramped 5+5 split.
2. **Contrast alternates pair-to-pair** — consecutive pairs alternate the visual contrast
   (the "context") between two levels: pair 0 → context A, pair 1 → context B, pair 2 → A, …
   So on top of the rewarded / non-rewarded odor discrimination, the context flips every pair.

To make rule 2 possible in a ``SequenceEnvironment`` (where a site's contrast lives in its
patch definition, and ``patch_indices`` only references patches by ``state_index``), the
graduated patch list is **duplicated once per context**: N patch definitions → ``N ×
len(CONTEXT_CONTRASTS)``. Context A holds the original 14 patches at contrast A; context B
holds identical copies (``state_index += N``, ``_ctx1`` label) at contrast B. The generated
sequence then references the context-A patches on even pairs and the context-B patches on odd
pairs. Everything stays a single block.

Where the base comes from
-------------------------
`graduated_task_logic()` returns the **real** graduated-stage task logic from
``aind_behavior_vr_foraging_curricula.learning_sets.stages.make_s_graduated`` — a
``SequenceEnvironment`` of single-reward-site patches over 7 odors (stop duration fixed at 3 s,
velocity at the floor, full geometry). That package is pulled in as a git dependency (see
``pyproject.toml``); this gist does not re-implement the learning sets, and reuses their
``get_odor_sequence`` pair generator verbatim.

⚠️ Worth reviewing
------------------
* The cross-session ``start_policies`` of the real graduated stage (``p_introduce_negative_sites``,
  ``p_water_cap``) are **dropped** here: this is a one-shot manual injection of a static
  ``TrainerState``, not a run through the ``Trainer``, so no policies fire. We only reuse the
  graduated stage's *task logic* (the environment) and the learning-set pair generator.
* You said the contrast context should go ``-0.5 -> 0.5``. The task schema constrains
  ``RenderSpecification.contrast`` to **[0, 1]**, so a literal ``-0.5`` will fail validation.
  ``CONTEXT_CONTRASTS`` below maps the two contexts onto that range — tune to taste.

Targets aind-behavior-vr-foraging >= 1.2 and aind-behavior-vr-foraging-curricula >= 1.2
(SequenceEnvironment / learning_sets API).
"""

from __future__ import annotations

import random

from aind_behavior_curriculum import Stage, TrainerState

import aind_behavior_vr_foraging.task_logic as vr
from aind_behavior_vr_foraging.task_logic import AindVrForagingTaskLogic
from aind_behavior_vr_foraging_curricula import __semver__ as _CURRICULA_VERSION
from aind_behavior_vr_foraging_curricula.learning_sets import helpers as ls
from aind_behavior_vr_foraging_curricula.learning_sets.curriculum import CURRICULUM_NAME as _BASE_CURRICULUM_NAME
from aind_behavior_vr_foraging_curricula.learning_sets.stages import make_s_graduated

# --------------------------------------------------------------------------------------
# Knobs to review
# --------------------------------------------------------------------------------------

#: The contrast "contexts" alternated pair-to-pair. Your intent was -0.5 / +0.5, but contrast
#: is bounded [0, 1] in the schema, so we map the two contexts onto that range. Each entry
#: becomes one duplicated copy of the graduated patch list; pairs cycle through them in order.
CONTEXT_CONTRASTS: tuple[float, float] = (0.5, 1.0)

#: Sites per odor pair ("block"). Y rewarded (positive) + Z non-rewarded (negative), shuffled
#: together. Fixed for every pair (unlike the graduated stage's ramped split).
REWARDED_PER_PAIR: int = 5  # Y
NON_REWARDED_PER_PAIR: int = 5  # Z

#: Number of odor pairs ("blocks") to generate for the session.
N_PAIRS: int = ls.N_PAIRS

#: Whether this suggestion should be flagged as generated by a curriculum. This is a manual,
#: off-curriculum injection, so False (the rig will still run `stage.task`, just logs a warning).
IS_ON_CURRICULUM: bool = False


# --------------------------------------------------------------------------------------
# Base: the real graduated stage of the LearningSets curriculum
# --------------------------------------------------------------------------------------

def _default_stage_name() -> str:
    """Descriptive default name, auto-filled from the knobs.

    Records the base curriculum this derives from (name + version), even though the injected
    ``TrainerState`` keeps ``curriculum=None`` / ``is_on_curriculum=False``.
    Example: ``manual_LearningSets_v1.2.0_2Contrasts_5Rew_5NonRew``.
    """
    return (
        f"manual_{_BASE_CURRICULUM_NAME}_v{_CURRICULA_VERSION}_"
        f"{len(CONTEXT_CONTRASTS)}Contrasts_"
        f"{REWARDED_PER_PAIR}Rew_{NON_REWARDED_PER_PAIR}NonRew"
    )


def graduated_task_logic() -> AindVrForagingTaskLogic:
    """Return the real graduated-stage task logic from the LearningSets curriculum.

    This is `aind_behavior_vr_foraging_curricula.learning_sets.stages.make_s_graduated`'s
    task: a `SequenceEnvironment` of 14 single-reward-site patches (7 odors × rewarded /
    non-rewarded) at the graduated settings (3 s stop, velocity floor, full geometry).
    """
    return make_s_graduated().task


# --------------------------------------------------------------------------------------
# Transforms: per-context patch copies + alternating-contrast pair sequence
# --------------------------------------------------------------------------------------

def _context_patches(base_patches: list[vr.Patch], contrast: float, offset: int, ctx: int) -> list[vr.Patch]:
    """One context's copy of the graduated patch list: deep-copied, ``state_index`` shifted by
    ``offset`` (so contexts don't collide), and every virtual-site generator set to ``contrast``."""
    out: list[vr.Patch] = []
    for p in base_patches:
        cp = p.model_copy(deep=True)
        cp.state_index = p.state_index + offset
        cp.label = f"{p.label}_ctx{ctx}"
        gens = cp.patch_virtual_sites_generator
        for gen in (gens.inter_site, gens.inter_patch, gens.reward_site, gens.post_patch):
            if gen is not None:
                gen.render_specification.contrast = contrast
        out.append(cp)
    return out


def _alternating_context_sequence(n_base: int, n_contexts: int) -> list[int]:
    """Build the ``patch_indices`` play order.

    Reuses the learning-set pair generator (``get_odor_sequence``). Each pair emits
    ``NON_REWARDED_PER_PAIR`` negative sites + ``REWARDED_PER_PAIR`` positive sites (shuffled),
    referencing the patches of the context selected by the pair's position (``i % n_contexts``).
    Negative variant ``state_index`` is ``neg``; positive variant is ``pos + ODOR_COUNT``; the
    context offset (``ctx * n_base``) then selects that context's copy.
    """
    sequence: list[int] = []
    for i, (neg, pos) in enumerate(ls.get_odor_sequence(total_trials=N_PAIRS, n=1)):
        offset = (i % n_contexts) * n_base
        pair_sites = (
            [neg + offset] * NON_REWARDED_PER_PAIR
            + [pos + ls.ODOR_COUNT + offset] * REWARDED_PER_PAIR
        )
        random.shuffle(pair_sites)
        sequence.extend(pair_sites)
    return sequence


# --------------------------------------------------------------------------------------
# Public entry point
# --------------------------------------------------------------------------------------

def build_trainer_state(stage_name: str | None = None) -> TrainerState:
    """Build the TrainerState to inject. Ignores any existing/incoming trainer state.

    Args:
        stage_name: optional name for the emitted stage.

    Returns:
        A TrainerState whose task is the real graduated learning-set stage, extended with one
        patch copy per context and a single-block sequence whose odor pairs alternate contrast.
    """
    graduated = graduated_task_logic()
    base_env = graduated.task_parameters.environment.blocks[0].environment
    assert isinstance(base_env, vr.SequenceEnvironment), (
        f"Expected the graduated stage to use a SequenceEnvironment, got {type(base_env).__name__}"
    )
    base_patches = base_env.patches
    n_base = len(base_patches)

    patches: list[vr.Patch] = []
    for ctx, contrast in enumerate(CONTEXT_CONTRASTS):
        patches.extend(_context_patches(base_patches, contrast, ctx * n_base, ctx))

    env = vr.SequenceEnvironment(
        patches=patches,
        sampling_mode=base_env.sampling_mode,
        patch_indices=_alternating_context_sequence(n_base, len(CONTEXT_CONTRASTS)),
    )

    task = graduated.model_copy(deep=True)
    task.task_parameters.environment = vr.BlockStructure(
        blocks=[vr.Block(environment=env)],
        sampling_mode="Sequential",
    )

    name = stage_name or _default_stage_name()
    task.stage_name = name
    stage = Stage(name=name, task=task)
    return TrainerState(
        stage=stage,
        curriculum=None,
        is_on_curriculum=IS_ON_CURRICULUM,
        active_policies=[],
    )


if __name__ == "__main__":
    # Quick self-check: build, round-trip, and verify the two rules hold.
    ts = build_trainer_state()
    blocks = ts.stage.task.task_parameters.environment.blocks
    env = blocks[0].environment
    n_base = len(env.patches) // len(CONTEXT_CONTRASTS)

    # state_index -> contrast, read off each patch's reward-site generator.
    contrast_of = {
        p.state_index: p.patch_virtual_sites_generator.reward_site.render_specification.contrast
        for p in env.patches
    }
    per_pair = REWARDED_PER_PAIR + NON_REWARDED_PER_PAIR
    idx = env.patch_indices
    n_pairs = len(idx) // per_pair

    prev_contrast = None
    for pair_i in range(min(n_pairs, 6)):  # spot-check the first few pairs
        chunk = idx[pair_i * per_pair : (pair_i + 1) * per_pair]
        rewarded = sum(1 for s in chunk if (s % n_base) >= ls.ODOR_COUNT)
        non_rewarded = per_pair - rewarded
        contrasts = {contrast_of[s] for s in chunk}
        assert rewarded == REWARDED_PER_PAIR, (pair_i, rewarded)
        assert non_rewarded == NON_REWARDED_PER_PAIR, (pair_i, non_rewarded)
        assert len(contrasts) == 1, (pair_i, contrasts)  # single context per pair
        c = contrasts.pop()
        assert c != prev_contrast, (pair_i, c)  # alternates pair-to-pair
        prev_contrast = c

    TrainerState.model_validate_json(ts.model_dump_json())  # raises if invalid
    print(
        f"OK: 1 block, {len(env.patches)} patches "
        f"({len(CONTEXT_CONTRASTS)} contexts × {n_base}), {n_pairs} pairs, "
        f"{per_pair}/pair ({REWARDED_PER_PAIR}+{NON_REWARDED_PER_PAIR}), contrasts alternate."
    )
